---

- name: Copy-files
  hosts: linux_nodes
  become: yes
  
  tasks:

   - name: Copy RedHat files
     copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
     loop:
       - { src: 'redhat-files/rfile1.txt', dest: '/etc/myfolder/'}
       - { src: 'redhat-files/rfile2.txt', dest: '/etc/myfolder/'}
     when: ansible_os_family == 'RedHat'

   - name: Copy Debian files
     copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
     loop:
       - { src: 'debian-files/dfile1.txt', dest: '/etc/myfolder/'}
       - { src: 'debian-files/dfile2.txt', dest: '/etc/myfolder/'}
     when: ansible_os_family == 'Debian'
